### ISSUE TITLE
Loottable bug

### ISSUE THREAD

**Issue by Lance5057** [Lance5057/Butchercraft#51]

**Comment by aldo94vp** [comment]
issue with https://www.curseforge.com/minecraft/mc-mods/apple-trees-revived (AppleTreesRev-Forge-1.18.2-v2.0.jar) apparently when both mods are together, loot is not working when using the tools on a carcass, this for forge 40.2.0 and mod version butchercraft-2.1.3.jar

```
[14:49:16] [Server thread/ERROR]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundUseItemOnPacket@24d8db27, suppressing error
java.lang.NullPointerException: Cannot read field "f_82479_" because "p_121873_" is null
	at net.minecraft.core.BlockPos.<init>(BlockPos.java:59) ~[client-1.18.2-20220404.173914-srg.jar%23125!/:?]
	at dav.mod.world.loot.GlobalLootModifiers$LuckyGlobalModifier.isContainerBlockEntityOrEntity(GlobalLootModifiers.java:68) ~[AppleTreesRev-Forge-1.18.2-v2.0.jar%2358!/:1.0]
	at dav.mod.world.loot.GlobalLootModifiers$LuckyGlobalModifier.doApply(GlobalLootModifiers.java:46) ~[AppleTreesRev-Forge-1.18.2-v2.0.jar%2358!/:1.0]
	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:39) ~[forge-1.18.2-40.2.0-universal.jar%23130!/:?]
	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1306) ~[forge-1.18.2-40.2.0-universal.jar%23130!/:?]
	at net.minecraft.world.level.storage.loot.LootTable.m_79129_(LootTable.java:89) ~[client-1.18.2-20220404.173914-srg.jar%23125!/:?]
	at com.lance5057.butchercraft.workstations.blockentities.MeatHookBlockEntity.dropLoot(MeatHookBlockEntity.java:268) ~[butchercraft-2.1.3.jar%2364!/:2.1.3]
	at com.lance5057.butchercraft.workstations.blockentities.MeatHookBlockEntity.butcher(MeatHookBlockEntity.java:227) ~[butchercraft-2.1.3.jar%2364!/:2.1.3]
	at com.lance5057.butchercraft.workstations.blocks.MeatHookBlock.m_6227_(MeatHookBlock.java:93) ~[butchercraft-2.1.3.jar%2364!/:2.1.3]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60664_(BlockBehaviour.java:697) ~[client-1.18.2-20220404.173914-srg.jar%23125!/:?]
	at net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameMode.java:342) ~[client-1.18.2-20220404.173914-srg.jar%23125!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerGamePacketListenerImpl.java:985) ~[client-1.18.2-20220404.173914-srg.jar%23125!/:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:30) ~[client-1.18.2-20220404.173914-srg.jar%23125!/:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:8) ~[client-1.18.2-20220404.173914-srg.jar%23125!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[client-1.18.2-20220404.173914-srg.jar%23125!/:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[client-1.18.2-20220404.173914-srg.jar%23125!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.18.2-20220404.173914-srg.jar%23125!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.18.2-20220404.173914-srg.jar%23125!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:799) ~[client-1.18.2-20220404.173914-srg.jar%23125!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:164) ~[client-1.18.2-20220404.173914-srg.jar%23125!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.18.2-20220404.173914-srg.jar%23125!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:782) ~[client-1.18.2-20220404.173914-srg.jar%23125!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:776) ~[client-1.18.2-20220404.173914-srg.jar%23125!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[client-1.18.2-20220404.173914-srg.jar%23125!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:762) ~[client-1.18.2-20220404.173914-srg.jar%23125!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:689) ~[client-1.18.2-20220404.173914-srg.jar%23125!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%23125!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```
