### ISSUE TITLE
Error and server/client desynchronization 

### ISSUE THREAD

**Issue by Hayk05** [Lance5057/Butchercraft#54]
This error occurs on the server, plus the players often have a mismatch between the items they need to freshen up, and which are displayed to them

```
[13:59:22] [Server thread/ERROR] [minecraft/PacketUtils]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundUseItemOnPacket@67f835f3, suppressing error
java.lang.NullPointerException: Cannot invoke "java.util.function.Consumer.accept(Object)" because "p_41625_" is null
        at net.minecraft.world.item.ItemStack.m_41622_(ItemStack.java:539) ~[server-1.18.2-20220404.173914-srg.jar%2379!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:forge:itemstack,re:classloading,pl:accesstransformer:B,xf:fml:forge:itemstack,pl:mixin:APP:bettercombat.mixins.json:ItemStackMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B,xf:fml:forge:itemstack,re:mixin,pl:accesstransformer:B,xf:fml:forge:itemstack}
        at com.lance5057.butchercraft.workstations.blockentities.MeatHookBlockEntity.butcher(MeatHookBlockEntity.java:234) ~[butchercraft-2.1.3.jar%2360!/:2.1.3] {re:classloading}
        at com.lance5057.butchercraft.workstations.blocks.MeatHookBlock.m_6227_(MeatHookBlock.java:93) ~[butchercraft-2.1.3.jar%2360!/:2.1.3] {re:classloading}
        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60664_(BlockBehaviour.java:705) ~[server-1.18.2-20220404.173914-srg.jar%2379!/:?] {re:mixin,re:classloading,pl:mixin:APP:tinkersurvival.mixins.json:AbstractBlockStateAccessor,pl:mixin:A}
        at net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameMode.java:543) ~[server-1.18.2-20220404.173914-srg.jar%2379!/:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerGamePacketListenerImpl.java:1336) ~[server-1.18.2-20220404.173914-srg.jar%2379!/:?] {re:mixin,re:classloading,pl:mixin:A,re:mixin}
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:30) ~[server-1.18.2-20220404.173914-srg.jar%2379!/:?] {re:classloading}
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:8) ~[server-1.18.2-20220404.173914-srg.jar%2379!/:?] {re:classloading}
        at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:26) ~[server-1.18.2-20220404.173914-srg.jar%2379!/:?] {re:classloading}
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.18.2-20220404.173914-srg.jar%2379!/:?] {re:classloading}
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.18.2-20220404.173914-srg.jar%2379!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.18.2-20220404.173914-srg.jar%2379!/:?] {re:mixin,re:computing_frames,re:classloading}
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:1096) ~[server-1.18.2-20220404.173914-srg.jar%2379!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:135) ~[server-1.18.2-20220404.173914-srg.jar%2379!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.18.2-20220404.173914-srg.jar%2379!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:1079) ~[server-1.18.2-20220404.173914-srg.jar%2379!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:1073) ~[server-1.18.2-20220404.173914-srg.jar%2379!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
        at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[server-1.18.2-20220404.173914-srg.jar%2379!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:1059) ~[server-1.18.2-20220404.173914-srg.jar%2379!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:945) ~[server-1.18.2-20220404.173914-srg.jar%2379!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:259) ~[server-1.18.2-20220404.173914-srg.jar%2379!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
        at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin}
[13:59:22] [Server thread/ERROR] [minecraft/PacketUtils]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundUseItemOnPacket@580f8fc, suppressing error
java.lang.NullPointerException: Cannot invoke "java.util.function.Consumer.accept(Object)" because "p_41625_" is null
        at net.minecraft.world.item.ItemStack.m_41622_(ItemStack.java:539) ~[server-1.18.2-20220404.173914-srg.jar%2379!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:forge:itemstack,re:classloading,pl:accesstransformer:B,xf:fml:forge:itemstack,pl:mixin:APP:bettercombat.mixins.json:ItemStackMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B,xf:fml:forge:itemstack,re:mixin,pl:accesstransformer:B,xf:fml:forge:itemstack}
        at com.lance5057.butchercraft.workstations.blockentities.MeatHookBlockEntity.butcher(MeatHookBlockEntity.java:234) ~[butchercraft-2.1.3.jar%2360!/:2.1.3] {re:classloading}
        at com.lance5057.butchercraft.workstations.blocks.MeatHookBlock.m_6227_(MeatHookBlock.java:93) ~[butchercraft-2.1.3.jar%2360!/:2.1.3] {re:classloading}
        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60664_(BlockBehaviour.java:705) ~[server-1.18.2-20220404.173914-srg.jar%2379!/:?] {re:mixin,re:classloading,pl:mixin:APP:tinkersurvival.mixins.json:AbstractBlockStateAccessor,pl:mixin:A}
        at net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameMode.java:543) ~[server-1.18.2-20220404.173914-srg.jar%2379!/:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerGamePacketListenerImpl.java:1336) ~[server-1.18.2-20220404.173914-srg.jar%2379!/:?] {re:mixin,re:classloading,pl:mixin:A,re:mixin}
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:30) ~[server-1.18.2-20220404.173914-srg.jar%2379!/:?] {re:classloading}
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:8) ~[server-1.18.2-20220404.173914-srg.jar%2379!/:?] {re:classloading}
        at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:26) ~[server-1.18.2-20220404.173914-srg.jar%2379!/:?] {re:classloading}
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.18.2-20220404.173914-srg.jar%2379!/:?] {re:classloading}
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.18.2-20220404.173914-srg.jar%2379!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.18.2-20220404.173914-srg.jar%2379!/:?] {re:mixin,re:computing_frames,re:classloading}
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:1096) ~[server-1.18.2-20220404.173914-srg.jar%2379!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:135) ~[server-1.18.2-20220404.173914-srg.jar%2379!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.18.2-20220404.173914-srg.jar%2379!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:1079) ~[server-1.18.2-20220404.173914-srg.jar%2379!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:1073) ~[server-1.18.2-20220404.173914-srg.jar%2379!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
        at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[server-1.18.2-20220404.173914-srg.jar%2379!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:1059) ~[server-1.18.2-20220404.173914-srg.jar%2379!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:945) ~[server-1.18.2-20220404.173914-srg.jar%2379!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:259) ~[server-1.18.2-20220404.173914-srg.jar%2379!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
        at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin}
```

**Comment by Lance5057** [comment]
I believe this is fixed?
